SQS_ACCESS_KEY_ID = "AKIAIIWU4BCL7KPESSIQ"
SQS_ACCESS_KEY_SECRET = "JpgO4hcNDlTMQVKdjimfnM9lHjPjHEaXDbn%2FrCbU"

BROKER_URL = "sqs://{0}:{1}@".format(SQS_ACCESS_KEY_ID, SQS_ACCESS_KEY_SECRET)

CELERY_RESULT_BACKEND = None

CELERY_IMPORTS = ("tasks", )

CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_RESULT_EXPIRES = None
